# FRONTEND SERVER
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend_server
spec:
  selector:
    matchLabels:
      app: frontend_server
  template:
    metadata:
      labels:
        app: frontend_server
    spec:
      containers:
      - name: frontend
        image: docker.io/dvduong/frontend:4
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend_server
spec:
  selector:
    app: frontend_server
  ports:
    - port: 5000