services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend_server
      - backend_server

  frontend_server: # Tên phải khớp với proxy_pass trong nginx.conf
    build: ./frontend
    # Không cần port ở đây vì đã có Nginx làm trung gian

  backend_server: # Tên phải khớp với proxy_pass trong nginx.conf
    build: ./backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres   # Thêm dòng này
      - POSTGRES_PASSWORD=pass   # Khớp với mật khẩu bên dưới
      - POSTGRES_DB=postgres     # Tên DB mặc định

    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
